include:
  - board: seeeduino_xiao_ble
    shield: pinkeybd_right
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: pinkeybd_left_
  - board: seeeduino_xiao_ble
    shield: settings_reset

